/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum19062025;

/**
 *
 * @author Asus
 */
public class MenuMinuman extends javax.swing.JFrame {
    
    private MenuUtama utama;

    /**
     * Creates new form MenuUtama
     */
    public MenuMinuman() {
        initComponents();
    }
    
    public MenuMinuman (MenuUtama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbBuah = new javax.swing.JCheckBox();
        cbSerut = new javax.swing.JCheckBox();
        cbTeh = new javax.swing.JCheckBox();
        cbKopi = new javax.swing.JCheckBox();
        btnReset = new javax.swing.JButton();
        chkBuah = new javax.swing.JComboBox<>();
        chkSerut = new javax.swing.JComboBox<>();
        chkTeh = new javax.swing.JComboBox<>();
        chkKopi = new javax.swing.JComboBox<>();
        txtBuah = new javax.swing.JTextField();
        txtSerut = new javax.swing.JTextField();
        txtTeh = new javax.swing.JTextField();
        txtKopi = new javax.swing.JTextField();
        txtTotBuah = new javax.swing.JTextField();
        txtTotSerut = new javax.swing.JTextField();
        txtTotTeh = new javax.swing.JTextField();
        txtTotKopi = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotHarga = new javax.swing.JButton();
        txtTotHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DAFTAR MENU MINUMAN");

        cbBuah.setText("Es Buah");
        cbBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuahActionPerformed(evt);
            }
        });

        cbSerut.setText("Es Serut");
        cbSerut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerutActionPerformed(evt);
            }
        });

        cbTeh.setText("Es Teh Manis");
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        cbKopi.setText("Coffe");
        cbKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKopiActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        chkBuah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        chkBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBuahActionPerformed(evt);
            }
        });

        chkSerut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        chkSerut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSerutActionPerformed(evt);
            }
        });

        chkTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        chkTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehActionPerformed(evt);
            }
        });

        chkKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        chkKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKopiActionPerformed(evt);
            }
        });

        txtBuah.setText("0");
        txtBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuahActionPerformed(evt);
            }
        });

        txtSerut.setText("0");

        txtTeh.setText("0");

        txtKopi.setText("0");

        txtTotBuah.setText("0");

        txtTotSerut.setText("0");

        txtTotTeh.setText("0");

        txtTotKopi.setText("0");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotHarga.setText("Total Harga");
        btnTotHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotHargaActionPerformed(evt);
            }
        });

        txtTotHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBuah)
                            .addComponent(cbSerut)
                            .addComponent(cbTeh)
                            .addComponent(cbKopi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKopi, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtTeh)
                            .addComponent(txtBuah)
                            .addComponent(txtSerut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTotHarga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chkKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotKopi))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chkTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotTeh))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chkSerut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotSerut))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chkBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotBuah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBuah)
                            .addComponent(chkBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSerut)
                            .addComponent(chkSerut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotSerut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTeh)
                            .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKopi)
                    .addComponent(chkKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotHarga)
                    .addComponent(txtTotHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuahActionPerformed
        int jml = (int)cbBuah.getSelectedIndex();
        double harga = Double.parseDouble(txtBuah.getText());
        double total = jml*harga;
        txtTotBuah.setText(Double.toString(total));
    }//GEN-LAST:event_cbBuahActionPerformed

    private void txtBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuahActionPerformed

    private void chkSerutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSerutActionPerformed
        txtSerut.setText("8000");
    }//GEN-LAST:event_chkSerutActionPerformed

    private void cbSerutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerutActionPerformed
        int jml = (int)cbSerut.getSelectedIndex();
        double harga = Double.parseDouble(txtSerut.getText());
        double total = jml*harga;
        txtTotSerut.setText(Double.toString(total));
    }//GEN-LAST:event_cbSerutActionPerformed

    private void btnTotHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotHargaActionPerformed
        double buah = Double.parseDouble(txtTotBuah.getText());
        double serut = Double.parseDouble(txtTotSerut.getText());
        double teh = Double.parseDouble(txtTotTeh.getText());
        double kopi = Double.parseDouble(txtTotKopi.getText());
        double total = buah + serut + kopi + teh;
        txtTotHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotHargaActionPerformed

    private void txtTotHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotHargaActionPerformed

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        int jml = (int)cbTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtTeh.getText());
        double total = jml*harga;
        txtTotTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehActionPerformed

    private void chkBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBuahActionPerformed
        txtBuah.setText("12000");
    }//GEN-LAST:event_chkBuahActionPerformed

    private void cbKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiActionPerformed
        int jml = (int)cbKopi.getSelectedIndex();
        double harga = Double.parseDouble(txtKopi.getText());
        double total = jml*harga;
        txtTotKopi.setText(Double.toString(total));
    }//GEN-LAST:event_cbKopiActionPerformed

    private void chkTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehActionPerformed
        txtTeh.setText("5000");
    }//GEN-LAST:event_chkTehActionPerformed

    private void chkKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKopiActionPerformed
        txtKopi.setText("8000");
    }//GEN-LAST:event_chkKopiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtBuah.setText("0");
        txtSerut.setText("0");
        txtTeh.setText("0");
        txtKopi.setText("0");
        cbBuah.setSelectedIndex(0);
        cbSerut.setSelectedIndex(0);
        cbTeh.setSelectedIndex(0);
        cbKopi.setSelectedIndex(0);
        txtTotHarga.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotHarga.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotHarga;
    private javax.swing.JCheckBox cbBuah;
    private javax.swing.JCheckBox cbKopi;
    private javax.swing.JCheckBox cbSerut;
    private javax.swing.JCheckBox cbTeh;
    private javax.swing.JComboBox<String> chkBuah;
    private javax.swing.JComboBox<String> chkKopi;
    private javax.swing.JComboBox<String> chkSerut;
    private javax.swing.JComboBox<String> chkTeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBuah;
    private javax.swing.JTextField txtKopi;
    private javax.swing.JTextField txtSerut;
    private javax.swing.JTextField txtTeh;
    private javax.swing.JTextField txtTotBuah;
    private javax.swing.JTextField txtTotHarga;
    private javax.swing.JTextField txtTotKopi;
    private javax.swing.JTextField txtTotSerut;
    private javax.swing.JTextField txtTotTeh;
    // End of variables declaration//GEN-END:variables
}
